# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_manager.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66ile_manager.proto\x12\x06protos\"2\n\x07Request\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x19\n\x11show_hidden_files\x18\x02 \x01(\x08\"G\n\x0f\x44ownloadRequest\x12\x17\n\rabsolute_path\x18\x01 \x01(\tH\x00\x12\x13\n\tfile_name\x18\x02 \x01(\tH\x00\x42\x06\n\x04path\"p\n\x08Response\x12\x0c\n\x04path\x18\x01 \x01(\t\x12$\n\x05\x66iles\x18\x02 \x03(\x0b\x32\x15.protos.Response.File\x1a\x30\n\x04\x46ile\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\t\"\"\n\x11\x46ileChunkResponse\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\x32\x89\x01\n\rFileExchanger\x12\x30\n\tListFiles\x12\x0f.protos.Request\x1a\x10.protos.Response\"\x00\x12\x46\n\x0c\x44ownloadFile\x12\x17.protos.DownloadRequest\x1a\x19.protos.FileChunkResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_manager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=30
  _globals['_REQUEST']._serialized_end=80
  _globals['_DOWNLOADREQUEST']._serialized_start=82
  _globals['_DOWNLOADREQUEST']._serialized_end=153
  _globals['_RESPONSE']._serialized_start=155
  _globals['_RESPONSE']._serialized_end=267
  _globals['_RESPONSE_FILE']._serialized_start=219
  _globals['_RESPONSE_FILE']._serialized_end=267
  _globals['_FILECHUNKRESPONSE']._serialized_start=269
  _globals['_FILECHUNKRESPONSE']._serialized_end=303
  _globals['_FILEEXCHANGER']._serialized_start=306
  _globals['_FILEEXCHANGER']._serialized_end=443
# @@protoc_insertion_point(module_scope)
