# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_manager.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66ile_manager.proto\"2\n\x07Request\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x19\n\x11show_hidden_files\x18\x02 \x01(\x08\"i\n\x08Response\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x1d\n\x05\x66iles\x18\x02 \x03(\x0b\x32\x0e.Response.File\x1a\x30\n\x04\x46ile\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\t23\n\rFileExchanger\x12\"\n\tListFiles\x12\x08.Request\x1a\t.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_manager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=22
  _globals['_REQUEST']._serialized_end=72
  _globals['_RESPONSE']._serialized_start=74
  _globals['_RESPONSE']._serialized_end=179
  _globals['_RESPONSE_FILE']._serialized_start=131
  _globals['_RESPONSE_FILE']._serialized_end=179
  _globals['_FILEEXCHANGER']._serialized_start=181
  _globals['_FILEEXCHANGER']._serialized_end=232
# @@protoc_insertion_point(module_scope)
